### ISSUE TITLE
How is this maintained?

### ISSUE THREAD

**Issue by pieterbeulque** [dlmma/webcomponentsjs#1]
Since the latest webcomponents commit was at the time of writing two days ago and your commit was nine months ago, I assume this is not really up to date?

Do you need help maintaining this?

**Comment by jadaradix** [comment]
It's not maintained and leads to https://github.com/Polymer/polymer-cli/issues/605 (for example).

Right now I'd recommend running `npm install webcomponents/webcomponentsjs`

Remember the paths have changed since this upload. I have seen code using feature detection to load `full.js` which now doesn't exist. Instead, see `webcomponents-loader.js`. I'm using that file to replace this old code:

```
        var webComponentsSupported = (
          'registerElement' in document &&
          'import' in document.createElement('link') &&
          'content' in document.createElement('template')
        );
        if (webComponentsSupported === false) {
          var script = document.createElement('script');
          script.async = true;
          script.src = 'node_modules/webcomponentsjs/full.js';
```

**Comment by jadaradix** [comment]
Polymer has the best advice I've found about polyfilling Custom Elements: https://www.polymer-project.org/2.0/docs/polyfills

They do it through Bower:

```
<script src="/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
```

I understand that _this_ repo exists so you can `npm install` webcomponentsjs and leave Bower in the past. However as above you can now run `npm install webcomponents/webcomponentsjs`!

After that, this HTML will do what you want:

```
<script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
```

This is a direct replacement for Polymer's Bower line.

Good luck!

**Comment by pieterbeulque** [comment]
Yes, I found this repository when I was looking for a way to use Polymer's polyfill in my client projects. Already made it work.

Thanks for your input, @jadaradix .
